name: coverageのサンプル

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    runs-on: ubuntu-latest
    services:
      swagger-petstore:
        image: swaggerapi/petstore3:unstable
        ports:
          - 8080:8080
    steps:
      - uses: actions/checkout@v4
      - name: Setup runn
        uses: k1LoW/gh-setup@v1
        with:
          repo: k1LoW/runn
      - name: test
        run: |
          runn run --verbose day18/open-api.yml
        env:
          PETSTORE3_END_POINT: http://172.17.0.1:8080/
      - name: Setup octocov-runn-coverage
        uses: k1LoW/gh-setup@v1
        with:
          repo: k1LoW/octocov-runn-coverage
      - name: Check out source code (main)
        uses: actions/checkout@v4
        with:
          ref: main
          path: main
      - name: coverage tests(main)
        continue-on-error: true
        run: |
          runn coverage --format json day18/open-api.yml | octocov-runn-coverage > custom_metrics_runn.json
        working-directory: main
      - name: Run octocov (main)
        continue-on-error: true
        uses: k1LoW/octocov-action@v1
        with:
          config: .octocov.runn.main.yml
        env:
          OCTOCOV_GITHUB_REF: refs/heads/main
          OCTOCOV_GITHUB_SHA: none
          OCTOCOV_CUSTOM_METRICS_BENCHMARK: main/custom_metrics_runn.json
      - name: coverage tests
        run: |
          runn coverage --format json day18/open-api.yml | octocov-runn-coverage > custom_metrics_runn.json
      - name: Run octocov
        uses: k1LoW/octocov-action@v1
        with:
          config: .octocov.runn.yml
        env:
          OCTOCOV_CUSTOM_METRICS_TEST: custom_metrics_runn.json
